"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { loadProjects,saveProjects,randomTitle } from "@/lib/storage";

export default function Dashboard(){
 const [projects,setProjects]=useState([]),[open,setOpen]=useState(false),[title,setTitle]=useState("");
 useEffect(()=>setProjects(loadProjects()),[]);
 function create(){const p={id:crypto.randomUUID(),title:title.trim()||randomTitle(),description:"",tags:[],topic:"",progress:0,updated:"Just now",step:"setup",ideas:[],sources:[],quotes:[],content:"<p>Begin your draft here…</p>"};const next=[p,...projects];saveProjects(next);location.href=`/project/${p.id}`}
 function remove(id){if(!confirm("Delete this project? This cannot be undone."))return;const next=projects.filter(p=>p.id!==id);setProjects(next);saveProjects(next)}
 return <main className="shell"><header className="topbar"><Link href="/" className="brand">flow<span className="brand-dot">.</span></Link><div className="row"><span className="muted">Demo student</span><div style={{width:34,height:34,borderRadius:99,background:"#dce6df",display:"grid",placeItems:"center"}}>D</div></div></header><section className="page"><div className="row" style={{justifyContent:"space-between",alignItems:"end",marginBottom:"2rem"}}><div><div className="eyebrow">Your workspace</div><h1 style={{fontSize:"3rem",marginBottom:8}}>Good afternoon.</h1><p className="muted">Pick up where you left off, or begin something new.</p></div><button className="btn" onClick={()=>setOpen(true)}>+ New project</button></div>{projects.length===0?<div className="card" style={{textAlign:"center",padding:"4rem"}}><h2>No projects yet</h2><p className="muted">Every strong paper begins with one small idea.</p><button className="btn" onClick={()=>setOpen(true)}>Create your first project</button></div>:<div className="grid">{projects.map(p=><article className="card project-card" key={p.id}><div><div className="row" style={{justifyContent:"space-between"}}><span className="eyebrow">{p.step||"setup"}</span><button className="btn ghost" aria-label="Delete project" onClick={()=>remove(p.id)}>×</button></div><h2>{p.title}</h2><p className="muted">{p.topic||p.description||"Ready for your first idea."}</p></div><div><div className="row" style={{justifyContent:"space-between",fontSize:12,marginBottom:7}}><span>{p.progress||0}% complete</span><span className="muted">{p.updated}</span></div><div className="progress"><span style={{width:`${p.progress||0}%`}}/></div><Link href={`/project/${p.id}`} className="btn secondary" style={{display:"block",textAlign:"center",marginTop:"1rem"}}>Continue</Link></div></article>)}</div>}</section>{open&&<div className="modal-backdrop"><div className="modal"><div className="eyebrow">New writing project</div><h2 style={{fontSize:"2rem",marginTop:8}}>What are you working on?</h2><input autoFocus className="field" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Project title (optional)" onKeyDown={e=>e.key==="Enter"&&create()}/><p className="muted" style={{fontSize:13}}>Leave this blank and Flow will give your project a temporary name.</p><div className="row" style={{justifyContent:"flex-end"}}><button className="btn secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn" onClick={create}>Create project</button></div></div></div>}</main>
}
