"use client";
import Link from "next/link";
import { use,useEffect,useRef,useState } from "react";
import { steps,tags } from "@/lib/demo-data";
import { loadProjects,saveProjects } from "@/lib/storage";
import DocumentEditor from "@/components/DocumentEditor";

const suggestions={Climate:["Local responses to climate change","Who bears the cost of extreme weather?"],History:["How public memory changes over time","Whose stories enter the historical record?"],Technology:["How technology changes student attention","The ethics of automated decision-making"],Literature:["How setting shapes identity in literature","The unreliable narrator and truth"]};
export default function Project({params}){
 const {id}=use(params),[project,setProject]=useState(null),[tab,setTab]=useState("setup"),[idea,setIdea]=useState(""),[url,setUrl]=useState(""),[quote,setQuote]=useState("");const saveTimer=useRef();
 useEffect(()=>{const p=loadProjects().find(x=>x.id===id);setProject(p);setTab(p?.step||"setup")},[id]);
 function update(patch){const next={...project,...patch,updated:"Just now"};setProject(next);clearTimeout(saveTimer.current);saveTimer.current=setTimeout(()=>{const all=loadProjects();saveProjects(all.map(p=>p.id===id?next:p))},250)}
 function go(next){const idx=steps.findIndex(s=>s.id===next);update({step:next,progress:Math.max(project.progress||0,Math.min(idx*25,100))});setTab(next)}
 function addIdea(text,origin="user"){if(!text.trim())return;update({ideas:[...(project.ideas||[]),text.trim()]});setIdea("")}
 function addSource(){if(!url.trim())return;let host="Source";try{host=new URL(url).hostname.replace("www.","")}catch{};update({sources:[...(project.sources||[]),{id:crypto.randomUUID(),url,title:`Article from ${host}`,publisher:host,author:"",score:url.startsWith("https")?55:35}]});setUrl("")}
 function addQuote(){if(!quote.trim())return;update({quotes:[...(project.quotes||[]),{text:quote,source:project.sources?.[0]?.title||"Manual note"}]});setQuote("")}
 if(!project)return <main className="page"><p>Loading project…</p></main>;
 return <main className="shell project-shell"><header className="topbar"><Link href="/dashboard" className="brand">flow<span className="brand-dot">.</span></Link><div className="row"><span className="muted">Saved automatically</span><button className="btn secondary" onClick={()=>window.print()}>Export / Print</button></div></header><div className="workspace"><aside className="side"><Link href="/dashboard" className="muted">← All projects</Link><h3 style={{marginTop:"2rem"}}>{project.title}</h3>{steps.map((s,i)=><button key={s.id} className={`step ${tab===s.id?"active":""} ${(project.progress||0)>i*25?"done":""}`} onClick={()=>setTab(s.id)}>{s.label}</button>)}</aside><section className={`work ${tab==="write"?"writing-work":""}`}>{tab==="setup"&&<Setup project={project} update={update} go={go}/>} {tab==="topic"&&<Topic project={project} update={update} addIdea={addIdea} idea={idea} setIdea={setIdea} go={go}/>} {tab==="research"&&<Research project={project} url={url} setUrl={setUrl} addSource={addSource} quote={quote} setQuote={setQuote} addQuote={addQuote} go={go}/>} {tab==="write"&&<Write project={project} update={update}/>} {tab==="calendar"&&<Calendar project={project} update={update}/>}</section><aside className="side right">{tab==="write"&&<><div className="eyebrow">Document settings</div><label className="sidebar-label">Citation format<select className="field" value={project.style||"MLA"} onChange={e=>update({style:e.target.value})}><option>MLA</option><option>APA</option><option>Chicago</option></select></label><button className="btn complete-writing" onClick={()=>go("calendar")}>Mark writing complete</button><hr className="sidebar-rule"/></>}<div className="eyebrow">Project notes</div><h3>Quote bank</h3>{tab==="write"&&project.quotes?.length>0&&<p className="drag-hint">Drag a quote onto the page to insert it with a citation.</p>}{project.quotes?.length?project.quotes.map((q,i)=><blockquote key={i} className={`bank-quote ${tab==="write"?"draggable":""}`} draggable={tab==="write"} onDragStart={e=>{const payload=JSON.stringify(q);e.dataTransfer.effectAllowed="copy";e.dataTransfer.setData("application/x-flow-quote",payload);e.dataTransfer.setData("text/plain",q.text)}}>“{q.text}”<small className="muted">{q.source}</small></blockquote>):<p className="muted">Quotes saved during research will appear here.</p>}<h3 style={{marginTop:"2rem"}}>Deadline</h3><p className="notice">{project.due?`Due ${project.due}`:"Add a due date in Calendar."}</p></aside></div></main>
}
function Header({eyebrow,title,children}){return <><div className="eyebrow">{eyebrow}</div><h1 style={{fontSize:"2.8rem",marginTop:8}}>{title}</h1>{children}</>}
function Setup({project,update,go}){return <><Header eyebrow="Checkpoint 1 of 4" title="Set up your project"><p className="muted">A working title is enough—you can change everything later.</p></Header><label>Project title<input className="field" value={project.title} onChange={e=>update({title:e.target.value})}/></label><label style={{display:"block",marginTop:"1rem"}}>Description<textarea className="field" rows="4" value={project.description||""} onChange={e=>update({description:e.target.value})} placeholder="What is the assignment or question?"/></label><h3 style={{marginTop:"1.5rem"}}>Categories</h3><div className="chips">{tags.map(t=><button className={`chip ${project.tags?.includes(t)?"on":""}`} key={t} onClick={()=>update({tags:project.tags?.includes(t)?project.tags.filter(x=>x!==t):[...(project.tags||[]),t]})}>{t}</button>)}</div><button className="btn" style={{marginTop:"2rem"}} onClick={()=>go("topic")}>Continue to topics →</button></>}
function Topic({project,update,addIdea,idea,setIdea,go}){const proposed=[...new Set((project.tags||[]).flatMap(t=>suggestions[t]||[]))].slice(0,6);return <><Header eyebrow="Checkpoint 2 of 4" title="Find an idea worth following"><p className="muted">Capture questions before judging them. Choose a direction when one starts pulling you in.</p></Header><div className="row"><input className="field" style={{flex:1}} value={idea} onChange={e=>setIdea(e.target.value)} placeholder="Type a question or topic…" onKeyDown={e=>e.key==="Enter"&&addIdea(idea)}/><button className="btn" onClick={()=>addIdea(idea)}>Add idea</button></div>{proposed.length>0&&<><h3 style={{marginTop:"1.5rem"}}>Prompts based on your categories</h3><div className="chips">{proposed.map(x=><button className="chip" key={x} onClick={()=>addIdea(x,"suggested")}>+ {x}</button>)}</div></>}<h3 style={{marginTop:"1.5rem"}}>Your idea cloud</h3><div className="bubble-wrap">{project.ideas?.length?project.ideas.map((x,i)=><button key={i} className="bubble" onClick={()=>update({topic:x})} style={project.topic===x?{outline:"3px solid #577565"}:{}}>{x}</button>):<p className="muted">Your ideas will gather here.</p>}</div><p className="muted">Click a bubble to choose it as your working topic.</p><button className="btn" disabled={!project.topic} onClick={()=>go("research")}>Continue to research →</button></>}
function Research({project,url,setUrl,addSource,quote,setQuote,addQuote,go}){return <><Header eyebrow="Checkpoint 3 of 4" title="Build your evidence"><p className="muted">Save useful sources and record exact quotations with their origin.</p></Header><div className="card"><h3>Add a web source</h3><div className="row"><input className="field" style={{flex:1}} value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…"/><button className="btn" onClick={addSource}>Fetch source</button></div><p className="muted" style={{fontSize:12}}>The demo records metadata locally. The server ingestion route validates and sanitizes URLs.</p></div><div className="source-list" style={{marginTop:"1rem"}}>{project.sources?.map(s=><article className="card source" key={s.id}><div className="row" style={{justifyContent:"space-between"}}><div><h3 style={{marginBottom:4}}>{s.title}</h3><span className="muted">{s.publisher}</span></div><span className="score">Credibility {s.score}/100</span></div></article>)}</div><div className="card" style={{marginTop:"1rem"}}><h3>Save a quotation or note</h3><textarea className="field" rows="3" value={quote} onChange={e=>setQuote(e.target.value)} placeholder="Paste the exact words here…"/><button className="btn secondary" style={{marginTop:8}} onClick={addQuote}>Add to quote bank</button></div><button className="btn" style={{marginTop:"1.5rem"}} onClick={()=>go("write")}>Continue to writing →</button></>}
function Write({project,update}){return <DocumentEditor project={project} onSave={update}/>}
function Calendar({project,update}){return <><Header eyebrow="Plan & finish" title="Keep the work moving"><p className="muted">Flow uses your due date to show calm, useful progress reminders.</p></Header><div className="card"><label>Submission due date<input type="date" className="field" value={project.due||""} onChange={e=>update({due:e.target.value})}/></label><label style={{display:"block",marginTop:"1rem"}}>Current status<select className="field" value={project.status||"active"} onChange={e=>update({status:e.target.value,progress:e.target.value==="completed"?100:project.progress})}><option value="active">In progress</option><option value="completed">Completed</option></select></label></div>{project.due&&<div className="notice" style={{marginTop:"1rem"}}>Your project is scheduled for {project.due}. Flow will flag incomplete checkpoints as the date approaches.</div>}</>}
